#!/bin/bash

# location of the javac command to use. Java 7 is currently the standard,
# Java 8 will compile but bring compatibility problems when running
JAVAC=javac

# location of the MIPAV installation to use
MIPAV="/var/tmp/mipav-7.3"

# additionally needed plugin classpath
PLUGINS_CP="$HOME/devel/cbstools/cbstools-deps/JIST-CRUISE-2017Mar30-12-05PM.jar"

# put users's paths together
CBS_CP=".:lib/*"
MIPAV_CP="$MIPAV:$MIPAV/jre/lib/*:$MIPAV/jre/lib/ext/*"
JAVAC_CP="$CBS_CP:$MIPAV_CP:$PLUGINS_CP"
JAVAC_OPTS="-Xlint:none -server -g -O -deprecation -encoding UTF-8"

$JAVAC  -cp "$JAVAC_CP" $JAVAC_OPTS ./de/mpg/cbs/core/*/*.java
$JAVAC  -cp "$JAVAC_CP" $JAVAC_OPTS ./de/mpg/cbs/*/*.java
#$JAVAC  -cp "$JAVAC_CP" $JAVAC_OPTS ./de/mpg/cbs/jist/*/*.java
$JAVAC  -cp "$JAVAC_CP" $JAVAC_OPTS ./edu/jhu/ece/iacl/jist/*/*.java

